# Generated by Django 3.0.2 on 2020-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
